linters:
    flake8:
        python: 3
        enable: true
        ignore: E203, E266, E501, W503, F401, E741
        max-line-length: 88
    shellcheck:
        shell: bash
    csslint:
        enable: false
files:
    ignore: ['versioneer.py', 'verde/_version.py', 'doc/conf.py']
