# Linting and style checks with GitHub Actions
#
# NOTE: Pin actions to a specific commit to avoid having the authentication
# token stolen if the Action is compromised. See the comments and links here:
# https://github.com/pypa/gh-action-pypi-publish/issues/27
#
name: code-style

# Only build PRs and the main branch. Pushes to branches will only be built
# when a PR is opened.
on:
  pull_request:
  push:
    branches:
      - main

###############################################################################
jobs:
  black:
    name: black [format]
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          persist-credentials: false

      - name: Setup Python
        uses: actions/setup-python@v2
        with:
          python-version: "3.8"

      - name: Install requirements
        run: python -m pip install -r env/requirements-style.txt

      - name: List installed packages
        run: python -m pip freeze

      - name: Check code format
        run: make black-check

  flake8:
    name: flake8 [style]
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          persist-credentials: false

      - name: Setup Python
        uses: actions/setup-python@v2
        with:
          python-version: "3.8"

      - name: Install requirements
        run: python -m pip install -r env/requirements-style.txt

      - name: List installed packages
        run: python -m pip freeze

      - name: Check code style
        run: make flake8

  pylint:
    name: pylint [style]
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          persist-credentials: false

      - name: Setup Python
        uses: actions/setup-python@v2
        with:
          python-version: "3.8"

      - name: Install requirements
        run: python -m pip install -r env/requirements-style.txt

      - name: List installed packages
        run: python -m pip freeze

      - name: Linting
        run: make lint

  license:
    name: license [format]
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          persist-credentials: false

      - name: Setup Python
        uses: actions/setup-python@v2
        with:
          python-version: "3.8"

      - name: Install requirements
        run: python -m pip install -r env/requirements-style.txt

      - name: List installed packages
        run: python -m pip freeze

      - name: Check license notice on all source files
        run: make license-check
